[[blockProviderConfigs]]

# motifs probably wouldn't even be defined in this file
# either it would be defined in the dungeons file or
# there isn't an object for it, it is simply an identifying name
# to categorize and tie dungeons and blockProviders together
# UPDATE a motif is applied to any defined dungeon config, so it
# would need it's own definition/class, but that can be in the
# dungeons config file.
[[blockProviderConfigs.motifs]]
	id="classic"
	biomeWhitelist=["*"]
	biomeBlacklist=[]


#=============================
#=============================
[[blockProviderConfigs.blockSets]]
	id="default"
	motif="classic"
	pattern="wall_pattern"
	[[blockProviderConfigs.blockSets.elements]]
		id="wall"
		block="minecraft:stone_bricks"
	[[blockProviderConfigs.blockSets.elements]]
		id="corner"
		block="minecraft:polished_andesite"
	[[blockProviderConfigs.blockSets.elements]]
		id="top_corner"
		block="minecraft:polished_andesite"

#=============================
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="floor_border_pattern"
	blockSet="default"
	[[blockProviderConfigs.blockSets.elements]]
		id="border"
		block="minecraft:polished_andesite"
	[[blockProviderConfigs.blockSets.elements]]
		id="center"
		block="minecraft:chiseled_stone_bricks"

#--------------------------------------------------
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="floor_border_pattern"
	blockSet="greek"
	[[blockProviderConfigs.blockSets.elements]]
		id="border"
		block="dungeonblocks:stone_greek_block"
	[[blockProviderConfigs.blockSets.elements]]
		id="center"
		block="minecraft:chiseled_stone_bricks"

#=============================
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="floor_drainage_pattern"
	blockSet="default"
	[[blockProviderConfigs.blockSets.elements]]
		id="corner"
		block="dungeonblocks:dark_iron_grate"
	[[blockProviderConfigs.blockSets.elements]]
		id="alternate_corner"
		block="dungeonblocks:weathered_copper_grate"
	[[blockProviderConfigs.blockSets.elements]]
		id="center"
		block="dungeonblocks:dark_iron_grate"
	[[blockProviderConfigs.blockSets.elements]]
		id="alternate_center"
		block="dungeonblocks:weathered_copper_grate"
	[[blockProviderConfigs.blockSets.elements]]
		id="gutter"
		block="dungeonblocks:weathered_copper_sewer_block"
	[[blockProviderConfigs.blockSets.elements]]
		id="alternate_gutter"
		block="dungeonblocks:terracotta_copper_sewer_block"

#=============================
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="ceiling_pattern"
	blockSet="default"
	[[blockProviderConfigs.blockSets.elements]]
		id="ceiling"
		block="minecraft:stone_bricks"

#=============================
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="corridor_ceiling_pattern"
	blockSet="default"
	[[blockProviderConfigs.blockSets.elements]]
		id="ceiling"
		block="minecraft:stone_bricks"

#=============================
[[blockProviderConfigs.blockSets]]
	motif="classic"
	pattern="door_pattern"
	blockSet="default"
	[[blockProviderConfigs.blockSets.elements]]
		id="door"
		block="dungeonblocks:spruce_dungeon_door"
	[[blockProviderConfigs.blockSets.elements]]
		id="lintel"
		block="minecraft:polished_andesite"
	[[blockProviderConfigs.blockSets.elements]]
		id="floor"
		block="minecraft:polished_andesite"
#=============================

[[blockProviderConfigs.decays]]
	from="minecraft:stone_bricks"
	to=["minecraft:mossy_stone_bricks", "minecraft:cracked_stone_bricks", "minecraft:cobblestone"]
[[blockProviderConfigs.decays]]
	from="minecraft:cobblestone"
	to=["minecraft:mossy_cobblestone","minecraft:gravel"]
[[blockProviderConfigs.decays]]
	from="minecraft:polished_andesite"
	to=["minecraft:andesite"]