#!/usr/bin/env python3
"""Build an Excel model of a processor list's decay rates, with LIVE formulas.

    python tools/weathering_rates.py src/main/resources/data/dungeons2/worldgen/processor_list/*.json -o out.xlsx

Every authored probability lands in its own blue cell; everything else is a formula off those
cells. So changing one number recalculates the whole block downstream -- the later stages of its
own chain, the shares of every rule below it on the same block, and the totals.

WHAT IT MODELS
--------------
The two compositions that make these files hard to read by eye:

  * A CHAIN (`output_blocks`, or a stage's own entry). Stage k only rolls if k-1 hit, and it
    REPLACES what k-1 produced, so what you see in the world is `reached x (1 - next stage's p)`.
  * A FORK (several rules on one source block). They are alternatives tried in authored order, so
    rule k is only offered what rules 1..k-1 declined. That is the `reach` column.

`agings` is a live cell too: raise or lower it and the stages past the cap drop to zero, which is
the truncation that is invisible in the JSON.

AND THE PIPELINE (#64)
----------------------
A processor list is CHAINED: entry N+1 sees entry N's output, so a block reaches an outcome by
several paths and the totals compound BETWEEN entries. That cannot be a live formula off the
per-entry sheets -- it is a Markov step per entry over the whole block distribution -- so each file
also gets a "pipeline" sheet of COMPUTED VALUES, regenerated by re-running this script.

It is the sheet that answers "what does a player actually see", and it is the only one that can:

  * an outcome a source reaches ONLY across entries (its own entry says 0%), and
  * an outcome whose end-to-end rate is materially above what its own rule's sheet shows.

`--self-test` checks the model against the worked examples in the Processor Manual.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

sys.path.insert(0, str(Path(__file__).parent))
from format_processor_list import strip_comments  # noqa: E402

FONT = "Arial"
INPUT_BLUE = Font(name=FONT, color="0000FF")
FORMULA = Font(name=FONT)
HEADER = Font(name=FONT, bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="404040")
BLOCK_FONT = Font(name=FONT, bold=True)
BLOCK_FILL = PatternFill("solid", fgColor="D9D9D9")
NOTE = Font(name=FONT, italic=True, color="808080")
PCT = "0.00%"

COLUMNS = [
    ("Source block", 42),
    ("Rule", 6),
    ("Stage", 6),
    ("Becomes", 42),
    ("Authored p", 12),
    ("Reach", 10),
    ("Reached", 10),
    ("Next p", 9),
    ("SURVIVES", 11),
    ("", 3),
    ("Target", 10),
    ("Author this", 12),
]


def rules_of(processor: dict) -> list[dict]:
    """Normalise both processor shapes to: source block, list of (output, probability)."""
    kind = processor["processor_type"]
    out = []
    if kind in ("dungeons2:aging", "dungeons2:surface_aging"):
        for rule in processor.get("rules", []):
            stages = [(s["block"], s["probability"]) for s in rule["output_blocks"]]
            out.append({"block": rule["block"], "stages": stages,
                        "surface": rule.get("surface", "")})
    elif kind == "minecraft:rule":
        for rule in processor.get("rules", []):
            predicate = rule["input_predicate"]
            block = predicate.get("block", "?")
            if ":" not in block:
                block = "minecraft:" + block
            out.append({"block": block,
                        "stages": [(rule["output_state"]["Name"],
                                    predicate.get("probability", 1.0))],
                        "surface": ""})
    return out


# ---------------------------------------------------------------------------------------------
# THE PIPELINE (#64). One Markov step per processor entry.
#
# The per-entry sheets above are correct and are not enough: a list is CHAINED, so entry N+1 sees
# entry N's output. Three consequences the sheets cannot show, all of them from the Processor
# Manual section 1:
#
#   * a source reaches an outcome by SEVERAL paths (stone_bricks reaches gravel through plain
#     cobblestone and again through mossy cobblestone), so the rates add;
#   * a later entry catches blocks that were ALREADY that block, not only the ones the entry above
#     produced -- the cross-contamination aging does not have;
#   * an outcome can be reachable ONLY across entries, which reads as 0% on every sheet.
#
# Within one entry nothing chains: rules on a block are alternatives tried in authored order (a
# miss falls through to the next), and only a rule's own `output_blocks` chain. That is exactly the
# reach/stage arithmetic the sheets use, so the step below is built from the same numbers.
# ---------------------------------------------------------------------------------------------

#: Rates below this are dropped from the pipeline sheet rather than shown as 0.00%.
FLOOR = 0.0005

#: An end-to-end rate this far above the rate the outcome's own entry shows is called out.
COMPOUND = 0.005


def applies(rule: dict, surface: str | None) -> bool:
    """Whether a rule runs on a cell of this surface class.

    An ungated rule (`surface` absent, or `any`) runs everywhere. A gated one runs only on its own
    class -- and per the manual, gates only partition a piece when EVERY rule in the file carries
    one, which is why the caller runs a separate pipeline per class rather than mixing them.
    """
    gate = rule.get("surface", "")
    return surface is None or gate in ("", "any", surface)


def transition(processor: dict, surface: str | None = None) -> dict[str, dict[str, float]]:
    """One entry as a transition: source block -> {outcome: probability}, each row summing to 1.

    The row includes the mass that stays put, which is what makes the rows composable.
    """
    cap = processor.get("agings", 99)
    rows: dict[str, dict[str, float]] = {}
    reaches: dict[str, float] = {}

    for rule in rules_of(processor):
        if not applies(rule, surface):
            continue
        stages = rule["stages"][:cap]          # `agings` truncates the chain, silently, in game too
        if not stages:
            continue
        block = rule["block"]
        row = rows.setdefault(block, {})
        reach = reaches.get(block, 1.0)        # the FORK: what every earlier rule on this block declined

        depth = reach * stages[0][1]
        for index, (output, _) in enumerate(stages):
            if index:
                depth *= stages[index][1]      # the CHAIN: stage k only rolls if k-1 hit
            following = stages[index + 1][1] if index + 1 < len(stages) else 0.0
            row[output] = row.get(output, 0.0) + depth * (1.0 - following)
        reaches[block] = reach * (1.0 - stages[0][1])

    for block, row in rows.items():
        row[block] = row.get(block, 0.0) + reaches[block]
    return rows


def step(distribution: dict[str, float], matrix: dict[str, dict[str, float]]) -> dict[str, float]:
    """Push a distribution through one entry. A block no rule names is carried through unchanged."""
    out: dict[str, float] = {}
    for block, mass in distribution.items():
        row = matrix.get(block)
        if row is None:
            out[block] = out.get(block, 0.0) + mass
            continue
        for outcome, probability in row.items():
            out[outcome] = out.get(outcome, 0.0) + mass * probability
    return out


def pipeline(processors: list[dict], surface: str | None = None):
    """End-to-end outcomes per source block, against what each outcome's OWN entry claims.

    Returns `{source: {outcome: (end_to_end, own_entry)}}`. `own_entry` is the rate the first entry
    that can make this outcome from this source shows on its own sheet -- i.e. the number an author
    reads today. Where the two differ, the difference is the compounding.
    """
    matrices = [transition(entry, surface) for entry in processors]
    sources = sorted({block for matrix in matrices for block in matrix})

    result = {}
    for source in sources:
        distribution = {source: 1.0}
        for matrix in matrices:
            distribution = step(distribution, matrix)
        own = {}
        for matrix in matrices:
            for outcome, probability in matrix.get(source, {}).items():
                own.setdefault(outcome, probability)   # the FIRST entry that could do it directly
        result[source] = {outcome: (mass, own.get(outcome, 0.0))
                          for outcome, mass in distribution.items() if mass >= FLOOR}
    return result


def surface_classes(processors: list[dict]) -> list[str | None]:
    """The surface classes a file partitions its piece into, or `[None]` when it does not gate."""
    classes = sorted({rule.get("surface", "") for entry in processors
                      for rule in entry.get("rules", [])} - {"", "any"})
    return list(classes) if classes else [None]


def sheet_for(workbook: Workbook, title: str, processor: dict, source_name: str):
    sheet = workbook.create_sheet(title[:31])
    rules = rules_of(processor)
    if not rules:
        return

    sheet["A1"] = processor["processor_type"]
    sheet["A1"].font = BLOCK_FONT
    sheet["A2"] = f"from {source_name}"
    sheet["A2"].font = NOTE

    # `agings` as a live cell: the truncation it causes is the one thing the JSON hides.
    sheet["E1"] = "agings"
    sheet["E1"].font = FORMULA
    sheet["F1"] = processor.get("agings", 99)
    sheet["F1"].font = INPUT_BLUE
    sheet["G1"] = "<- a stage numbered above this never fires"
    sheet["G1"].font = NOTE

    header_row = 4
    for index, (name, width) in enumerate(COLUMNS, start=1):
        cell = sheet.cell(row=header_row, column=index, value=name)
        cell.font = HEADER
        if name:
            cell.fill = HEADER_FILL
        sheet.column_dimensions[get_column_letter(index)].width = width

    # Group by source block, preserving authored order -- fork position is the whole point.
    grouped: dict[str, list[dict]] = {}
    for rule in rules:
        grouped.setdefault(rule["block"], []).append(rule)

    row = header_row + 1
    for block, block_rules in grouped.items():
        first_row_of_block = row
        stage_one_rows = []
        survive_rows = []

        for rule_index, rule in enumerate(block_rules, start=1):
            for stage_index, (output, probability) in enumerate(rule["stages"], start=1):
                sheet.cell(row=row, column=1,
                           value=block + (f"  [{rule['surface']}]" if rule["surface"] else "")
                           if stage_index == 1 and rule_index == 1 else "").font = FORMULA
                sheet.cell(row=row, column=2, value=rule_index).font = FORMULA
                sheet.cell(row=row, column=3, value=stage_index).font = FORMULA
                sheet.cell(row=row, column=4, value=output).font = FORMULA

                authored = sheet.cell(row=row, column=5, value=probability)
                authored.font = INPUT_BLUE
                authored.number_format = "0.0000"

                # REACH -- what fraction of the block is still unclaimed when this cell rolls.
                if stage_index > 1:
                    reach = f"=G{row - 1}"                      # the stage above me was reached
                elif rule_index == 1:
                    reach = "=1"                                # nothing has had a turn yet
                else:
                    prior = stage_one_rows[-1]
                    reach = f"=F{prior}*(1-E{prior})"           # the fork: what rule k-1 declined
                sheet.cell(row=row, column=6, value=reach).font = FORMULA
                sheet.cell(row=row, column=6).number_format = PCT

                # REACHED -- and the agings cap, live off F1.
                sheet.cell(row=row, column=7,
                           value=f"=IF(C{row}>$F$1,0,F{row}*E{row})").font = FORMULA
                sheet.cell(row=row, column=7).number_format = PCT

                # NEXT P -- the stage that would replace this one, 0 if this is the last.
                has_next = stage_index < len(rule["stages"])
                next_p = f"=IF(C{row + 1}>$F$1,0,E{row + 1})" if has_next else "=0"
                sheet.cell(row=row, column=8, value=next_p).font = FORMULA
                sheet.cell(row=row, column=8).number_format = "0.0000"

                # SURVIVES -- what a player actually sees, net of the next stage firing instead.
                survives = sheet.cell(row=row, column=9, value=f"=G{row}*(1-H{row})")
                survives.font = FORMULA
                survives.number_format = PCT
                survive_rows.append(row)

                # The fork formula, live: type the share you want, read the number to author.
                if stage_index == 1:
                    sheet.cell(row=row, column=11).font = INPUT_BLUE
                    sheet.cell(row=row, column=11).number_format = PCT
                    sheet.cell(row=row, column=12,
                               value=f'=IF(K{row}="","",K{row}/F{row})').font = FORMULA
                    sheet.cell(row=row, column=12).number_format = "0.0000"
                    stage_one_rows.append(row)

                row += 1

        total = sheet.cell(row=row, column=4, value="changed / unchanged")
        total.font = BLOCK_FONT
        total.alignment = Alignment(horizontal="right")
        changed = "+".join(f"I{r}" for r in survive_rows)
        sheet.cell(row=row, column=9, value=f"={changed}").font = BLOCK_FONT
        sheet.cell(row=row, column=9).number_format = PCT
        sheet.cell(row=row, column=8, value=f"=1-({changed})").font = BLOCK_FONT
        sheet.cell(row=row, column=8).number_format = PCT
        for column in range(1, 10):
            sheet.cell(row=row, column=column).fill = BLOCK_FILL
        row += 2

        _ = first_row_of_block

    sheet.freeze_panes = f"A{header_row + 1}"


PIPELINE_COLUMNS = [
    ("Source block", 42),
    ("Ends up as", 42),
    ("END TO END", 12),
    ("Its own entry", 13),
    ("Difference", 11),
    ("", 3),
    ("What that means", 46),
]


def pipeline_sheet(workbook: Workbook, title: str, processors: list[dict], source_name: str):
    """The whole list run end to end. VALUES, not formulas -- see the header it writes."""
    sheet = workbook.create_sheet(title[:31])

    sheet["A1"] = "PIPELINE -- the whole list, end to end"
    sheet["A1"].font = BLOCK_FONT
    sheet["A2"] = f"from {source_name}"
    sheet["A2"].font = NOTE
    sheet["A3"] = ("Computed VALUES, not live formulas: a chained list is a Markov step per entry, "
                   "not arithmetic off one sheet. Re-run tools/weathering_rates.py after editing "
                   "any blue cell.")
    sheet["A3"].font = NOTE

    row = 5
    findings = []
    for surface in surface_classes(processors):
        if surface is not None:
            label = sheet.cell(row=row, column=1, value=f"surface: {surface}")
            label.font = BLOCK_FONT
            sheet.cell(row=row, column=2,
                       value="a separate population -- gated rules only partition the piece when "
                             "EVERY rule carries a gate").font = NOTE
            row += 1

        header_row = row
        for index, (name, width) in enumerate(PIPELINE_COLUMNS, start=1):
            cell = sheet.cell(row=header_row, column=index, value=name)
            cell.font = HEADER
            if name:
                cell.fill = HEADER_FILL
            sheet.column_dimensions[get_column_letter(index)].width = width
        row += 1

        for source, outcomes in pipeline(processors, surface).items():
            first = True
            ordered = sorted(outcomes.items(), key=lambda item: -item[1][0])
            for outcome, (end_to_end, own) in ordered:
                unchanged = outcome == source
                sheet.cell(row=row, column=1, value=source if first else "").font = FORMULA
                sheet.cell(row=row, column=2,
                           value="(unchanged)" if unchanged else outcome).font = FORMULA
                for column, value in ((3, end_to_end), (4, None if unchanged else own),
                                      (5, None if unchanged else end_to_end - own)):
                    cell = sheet.cell(row=row, column=column, value=value)
                    cell.font = FORMULA
                    cell.number_format = PCT

                note = ""
                if not unchanged and own < FLOOR and end_to_end >= FLOOR:
                    note = "ONLY reachable across entries -- reads 0% on every sheet"
                    findings.append((source, outcome, end_to_end, own, note))
                elif not unchanged and end_to_end - own >= COMPOUND:
                    note = "compounds -- several paths reach it"
                    findings.append((source, outcome, end_to_end, own, note))
                cell = sheet.cell(row=row, column=7, value=note)
                cell.font = BLOCK_FONT if note else FORMULA

                first = False
                row += 1
            row += 1

    sheet.freeze_panes = "A5"
    return findings


def notes_sheet(workbook: Workbook, files: list[str]):
    sheet = workbook.create_sheet("Read me", 0)
    sheet.column_dimensions["A"].width = 110
    lines = [
        ("Dungeons2 weathering rates", BLOCK_FONT),
        ("", FORMULA),
        ("BLUE cells are the authored numbers -- the ones that exist in the JSON. Edit those.", FORMULA),
        ("Everything black is a formula. Change a blue cell and the sheet recomputes downstream.", FORMULA),
        ("", FORMULA),
        ("Reach     what fraction of the source block is still unclaimed when this rule rolls.", FORMULA),
        ("          Rule 1 gets 100%; rule 2 only gets what rule 1 declined. That is the FORK.", FORMULA),
        ("Reached   probability the block gets at least this deep = Reach x Authored p.", FORMULA),
        ("Next p    the stage that would replace this one (0 if it is the last).", FORMULA),
        ("SURVIVES  what a player actually sees = Reached x (1 - Next p). This is the column", FORMULA),
        ("          to compare against the game.", FORMULA),
        ("", FORMULA),
        ("TARGET / AUTHOR THIS -- the fork formula, live. Type the share you want a rule to take", FORMULA),
        ("into Target and 'Author this' gives the probability to put in the JSON. It is", FORMULA),
        ("target / reach, which is why only the first rule on a block can be authored at its", FORMULA),
        ("face value.", FORMULA),
        ("", FORMULA),
        ("agings (cell F1 of each sheet) is live. Lower it and stages past the cap fall to zero --", FORMULA),
        ("that truncation is invisible in the JSON and is a real bug that has shipped.", FORMULA),
        ("", FORMULA),
        ("THE PIPELINE SHEETS", BLOCK_FONT),
        ("A list is CHAINED: entry N+1 sees entry N's output. So a block reaches an outcome by more", FORMULA),
        ("than one path, the rates compound between entries, and a later entry also catches blocks", FORMULA),
        ("that were ALREADY that block rather than only the ones the entry above produced.", FORMULA),
        ("", FORMULA),
        ("Each file therefore has a 'pipeline' sheet running the whole list end to end, with what", FORMULA),
        ("each outcome's OWN entry claims beside it. Two things only that sheet can show:", FORMULA),
        ("  - an outcome reachable ONLY across entries, which reads 0% on every other sheet;", FORMULA),
        ("  - an outcome whose real rate is materially above its own rule's SURVIVES.", FORMULA),
        ("", FORMULA),
        ("Those sheets are COMPUTED VALUES, not formulas -- a Markov step per entry is not", FORMULA),
        ("arithmetic off one sheet. Edit a blue cell and re-run tools/weathering_rates.py.", FORMULA),
        ("", FORMULA),
        ("A file whose rules carry a `surface` gets one pipeline PER surface class, because gated", FORMULA),
        ("rules only partition a piece when every rule in the file carries a gate.", FORMULA),
        ("", FORMULA),
        ("Generated by tools/weathering_rates.py from:", NOTE),
    ]
    for index, (text, font) in enumerate(lines, start=1):
        cell = sheet.cell(row=index, column=1, value=text)
        cell.font = font
    for offset, name in enumerate(files):
        cell = sheet.cell(row=len(lines) + 1 + offset, column=1, value="    " + name)
        cell.font = NOTE


def self_test() -> int:
    """Check the model against the worked examples in the Processor Manual, section 1.

    The manual is where these numbers were reasoned out and argued over; if the simulator disagrees
    with it, one of the two is wrong and it needs saying out loud rather than shipping a workbook
    that quietly contradicts the document authors are told to read.
    """
    failures = []

    def check(label, got, want, tolerance=5e-5):
        if abs(got - want) > tolerance:
            failures.append(f"{label}: got {got:.6f}, manual says {want:.6f}")

    # "Down a chain" -- the cobblestone table.
    chain = {"processor_type": "dungeons2:aging", "agings": 99, "rules": [
        {"block": "cobblestone", "output_blocks": [
            {"block": "mossy_cobblestone", "probability": 0.30},
            {"block": "rubble", "probability": 0.25},
            {"block": "dirt", "probability": 0.25}]}]}
    row = transition(chain)["cobblestone"]
    check("chain mossy", row["mossy_cobblestone"], 0.225)
    check("chain rubble", row["rubble"], 0.05625)
    check("chain dirt", row["dirt"], 0.01875)
    check("chain untouched", row["cobblestone"], 0.70)

    # `agings` truncates: the manual's silent-truncation trap, capped to two stages.
    capped = transition(dict(chain, agings=2))["cobblestone"]
    check("capped rubble", capped["rubble"], 0.075)
    check("capped dirt", capped.get("dirt", 0.0), 0.0)

    # "Across a fork" -- 30% / 30% is authored 0.30 then 0.43.
    fork = {"processor_type": "dungeons2:aging", "rules": [
        {"block": "b", "output_blocks": [{"block": "one", "probability": 0.30}]},
        {"block": "b", "output_blocks": [{"block": "two", "probability": 0.43}]}]}
    row = transition(fork)["b"]
    check("fork rule 1", row["one"], 0.30)
    check("fork rule 2", row["two"], 0.301, 0.002)

    # "To build a real multi-stage chain out of vanilla rules, give each stage its own entry":
    # three entries at 0.3 put 2.7% of the original block at the end.
    def rule_entry(source, target, probability):
        return {"processor_type": "minecraft:rule", "rules": [
            {"input_predicate": {"predicate_type": "minecraft:random_block_match",
                                 "block": source, "probability": probability},
             "output_state": {"Name": target}}]}

    entries = [rule_entry("minecraft:stone", "minecraft:cobblestone", 0.3),
               rule_entry("minecraft:cobblestone", "minecraft:gravel", 0.3),
               rule_entry("minecraft:gravel", "minecraft:air", 0.3)]
    ends = pipeline(entries)["minecraft:stone"]
    check("three entries end to end", ends["minecraft:air"][0], 0.027)
    check("and its own entry claims nothing", ends["minecraft:air"][1], 0.0)

    # Cross-contamination: the last entry catches gravel that was gravel all along, so seeding
    # gravel gives the authored 30% while seeding stone gives 2.7%. Same rule, two answers.
    check("a source already at the outcome's input",
          pipeline(entries)["minecraft:gravel"]["minecraft:air"][0], 0.3)

    for failure in failures:
        print("FAIL " + failure, file=sys.stderr)
    print(f"self-test: {'FAILED' if failures else 'ok'}"
          f" ({len(failures)} disagreements with the Processor Manual)")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="*", type=Path)
    parser.add_argument("-o", "--out", type=Path)
    parser.add_argument("--self-test", action="store_true",
                        help="check the model against the Processor Manual's worked examples")
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if not args.files or not args.out:
        parser.error("files and -o/--out are required unless --self-test is given")

    workbook = Workbook()
    workbook.remove(workbook.active)
    findings = []

    for path in args.files:
        data = json.loads(strip_comments(path.read_text(encoding="utf-8")))
        short = path.stem.replace("classic_", "").replace("_weathering", "")
        counter = 0
        for processor in data["processors"]:
            if not processor.get("rules"):
                continue
            counter += 1
            kind = processor["processor_type"].split(":")[-1].replace("_", " ")
            sheet_for(workbook, f"{short} {counter} {kind}", processor, path.name)

        # The pipeline, once per file: it is the whole list, not one entry of it.
        entries = [p for p in data["processors"] if p.get("rules")]
        if entries:
            found = pipeline_sheet(workbook, f"{short} PIPELINE", entries, path.name)
            findings += [(path.name,) + f for f in found]

    notes_sheet(workbook, [str(f) for f in args.files])
    args.out.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(args.out)
    print(f"wrote {args.out} ({len(workbook.sheetnames)} sheets)")

    # Print them too. The finding is the point of the sheet, and it should not need Excel to see.
    if findings:
        print(f"\n{len(findings)} rate(s) the per-entry sheets understate:")
        for name, source, outcome, end_to_end, own, note in findings:
            print(f"  {name}: {source} -> {outcome}"
                  f"  end-to-end {end_to_end:6.2%}  its own entry {own:6.2%}   {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
